/**
 * @file Defines action type constants for Redux actions.
 * Includes authentication, onboarding, theme management, dashboard operations,
 * profile image uploads, and admin/doctor-specific actions.
 * @namespace store.actions.types
 * @memberof store.actions
 */

/** Theme Management */
export const SET_THEME = "SET_THEME";
export const SET_THEME_SUCCESS = "SET_THEME_SUCCESS";

/** Dashboard */
export const FETCH_DASHBOARD = "FETCH_DASHBOARD";
export const FETCH_DASHBOARD_PENDING = "FETCH_DASHBOARD_PENDING";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_ERROR = "FETCH_DASHBOARD_ERROR";

/** Dashboard */
export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_PENDING = "FETCH_PROFILE_PENDING";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_ERROR = "FETCH_PROFILE_ERROR";

/** Authentication */
export const SET_USER_AUTH = "SET_USER_AUTH";
export const LOGOUT_USER = "LOGOUT_USER";

/** Login */
export const LOGIN = "LOGIN";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

/** OAuth Login */
export const OAUTH_LOGIN = "OAUTH_LOGIN";
export const OAUTH_LOGIN_PENDING = "OAUTH_LOGIN_PENDING";
export const OAUTH_LOGIN_SUCCESS = "OAUTH_LOGIN_SUCCESS";
export const OAUTH_LOGIN_ERROR = "OAUTH_LOGIN_ERROR";

/** Signup */
export const SIGNUP = "SIGNUP";
export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

/** OAuth Signup */
export const OAUTH_SIGNUP = "OAUTH_SIGNUP";
export const OAUTH_SIGNUP_PENDING = "OAUTH_SIGNUP_PENDING";
export const OAUTH_SIGNUP_SUCCESS = "OAUTH_SIGNUP_SUCCESS";
export const OAUTH_SIGNUP_ERROR = "OAUTH_SIGNUP_ERROR";

/** Doctor Onboarding */
export const DOCTOR_ONBOARDING = "DOCTOR_ONBOARDING";
export const DOCTOR_ONBOARDING_PENDING = "DOCTOR_ONBOARDING_PENDING";
export const DOCTOR_ONBOARDING_SUCCESS = "DOCTOR_ONBOARDING_SUCCESS";
export const DOCTOR_ONBOARDING_ERROR = "DOCTOR_ONBOARDING_ERROR";

/** Patient Onboarding */
export const PATIENT_ONBOARDING = "PATIENT_ONBOARDING";
export const PATIENT_ONBOARDING_PENDING = "PATIENT_ONBOARDING_PENDING";
export const PATIENT_ONBOARDING_SUCCESS = "PATIENT_ONBOARDING_SUCCESS";
export const PATIENT_ONBOARDING_ERROR = "PATIENT_ONBOARDING_ERROR";

/** Role Selection */
export const ROLE_SELECION = "ROLE_SELECION";

/** Profile Image Upload */
export const UPLOAD_PROFILE_IMAGE = "UPLOAD_PROFILE_IMAGE";
export const UPLOAD_PROFILE_IMAGE_PENDING = "UPLOAD_PROFILE_IMAGE_PENDING";
export const UPLOAD_PROFILE_IMAGE_SUCCESS = "UPLOAD_PROFILE_IMAGE_SUCCESS";
export const UPLOAD_PROFILE_IMAGE_ERROR = "UPLOAD_PROFILE_IMAGE_ERROR";

export const FETCH_PROFILE_IMAGE = "FETCH_PROFILE_IMAGE";
export const FETCH_PROFILE_IMAGE_PENDING = "FETCH_PROFILE_IMAGE_PENDING";
export const FETCH_PROFILE_IMAGE_SUCCESS = "FETCH_PROFILE_IMAGE_SUCCESS";
export const FETCH_PROFILE_IMAGE_ERROR = "FETCH_PROFILE_IMAGE_ERROR";

/** Admin Actions */
export const FETCH_DOCTORS = "FETCH_DOCTORS";
export const FETCH_DOCTORS_PENDING = "FETCH_DOCTORS_PENDING";
export const FETCH_DOCTORS_SUCCESS = "FETCH_DOCTORS_SUCCESS";
export const FETCH_DOCTORS_ERROR = "FETCH_DOCTORS_ERROR";

export const VERIFY_DOCTOR = "VERIFY_DOCTOR";
export const VERIFY_DOCTOR_PENDING = "VERIFY_DOCTOR_PENDING";
export const VERIFY_DOCTOR_SUCCESS = "VERIFY_DOCTOR_SUCCESS";
export const VERIFY_DOCTOR_ERROR = "VERIFY_DOCTOR_ERROR";

/** Doctor Actions */
export const UPLOAD_VERIFICATION_DOCS = "UPLOAD_VERIFICATION_DOCS";
export const UPLOAD_VERIFICATION_DOCS_PENDING =
  "UPLOAD_VERIFICATION_DOCS_PENDING";
export const UPLOAD_VERIFICATION_DOCS_SUCCESS =
  "UPLOAD_VERIFICATION_DOCS_SUCCESS";
export const UPLOAD_VERIFICATION_DOCS_ERROR = "UPLOAD_VERIFICATION_DOCS_ERROR";

/** Fetch Health Issue Actions */
export const FETCH_HEALTH_ISSUES = "FETCH_HEALTH_ISSUES";
export const FETCH_HEALTH_ISSUES_PENDING = "FETCH_HEALTH_ISSUES_PENDING";
export const FETCH_HEALTH_ISSUES_SUCCESS = "FETCH_HEALTH_ISSUES_SUCCESS";
export const FETCH_HEALTH_ISSUES_ERROR = "FETCH_HEALTH_ISSUES_ERROR";

/** Add Health Issue Actions */
export const ADD_HEALTH_ISSUE = "ADD_HEALTH_ISSUE";
export const ADD_HEALTH_ISSUE_PENDING = "ADD_HEALTH_ISSUE_PENDING";
export const ADD_HEALTH_ISSUE_SUCCESS = "ADD_HEALTH_ISSUE_SUCCESS";
export const ADD_HEALTH_ISSUE_ERROR = "ADD_HEALTH_ISSUE_ERROR";

/** Forgot Password */
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_PENDING = "FORGOT_PASSWORD_PENDING";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

// Insurance
export const CREATE_INSURANCE = "CREATE_INSURANCE";
export const CREATE_INSURANCE_PENDING = "CREATE_INSURANCE_PENDING";
export const CREATE_INSURANCE_SUCCESS = "CREATE_INSURANCE_SUCCESS";
export const CREATE_INSURANCE_ERROR = "CREATE_INSURANCE_ERROR";

export const FETCH_INSURANCE = "FETCH_INSURANCE";
export const FETCH_INSURANCE_PENDING = "FETCH_INSURANCE_PENDING";
export const FETCH_INSURANCE_SUCCESS = "FETCH_INSURANCE_SUCCESS";
export const FETCH_INSURANCE_ERROR = "FETCH_INSURANCE_ERROR";

export const UPDATE_PATIENT_PROFILE = "UPDATE_PATIENT_PROFILE";
export const UPDATE_PATIENT_PROFILE_PENDING = "UPDATE_PATIENT_PROFILE_PENDING";
export const UPDATE_PATIENT_PROFILE_SUCCESS = "UPDATE_PATIENT_PROFILE_SUCCESS";
export const UPDATE_PATIENT_PROFILE_ERROR = "UPDATE_PATIENT_PROFILE_ERROR";

export const UPDATE_DOCTOR_PROFILE = "UPDATE_DOCTOR_PROFILE";
export const UPDATE_DOCTOR_PROFILE_PENDING = "UPDATE_DOCTOR_PROFILE_PENDING";
export const UPDATE_DOCTOR_PROFILE_SUCCESS = "UPDATE_DOCTOR_PROFILE_SUCCESS";
export const UPDATE_DOCTOR_PROFILE_ERROR = "UPDATE_DOCTOR_PROFILE_ERROR";

export const CREATE_MEDICAL_HISTORY = "CREATE_MEDICAL_HISTORY";
export const CREATE_MEDICAL_HISTORY_PENDING = "CREATE_MEDICAL_HISTORY_PENDING";
export const CREATE_MEDICAL_HISTORY_SUCCESS = "CREATE_MEDICAL_HISTORY_SUCCESS";
export const CREATE_MEDICAL_HISTORY_ERROR = "CREATE_MEDICAL_HISTORY_ERROR";


export const FETCH_MEDICAL_HISTORY = "FETCH_MEDICAL_HISTORY";
export const FETCH_MEDICAL_HISTORY_PENDING = "FETCH_MEDICAL_HISTORY_PENDING";
export const FETCH_MEDICAL_HISTORY_SUCCESS = "FETCH_MEDICAL_HISTORY_SUCCESS";
export const FETCH_MEDICAL_HISTORY_ERROR = "FETCH_MEDICAL_HISTORY_ERROR";


// Appointments
export const FETCH_APPOINTMENTS = "FETCH_APPOINTMENTS";
export const FETCH_APPOINTMENTS_PENDING = "FETCH_APPOINTMENTS_PENDING";
export const FETCH_APPOINTMENTS_SUCCESS = "FETCH_APPOINTMENTS_SUCCESS";
export const FETCH_APPOINTMENTS_ERROR = "FETCH_APPOINTMENTS_ERROR";

export const CREATE_APPOINTMENT = "CREATE_APPOINTMENT";
export const CREATE_APPOINTMENT_PENDING = "CREATE_APPOINTMENT_PENDING";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_ERROR = "CREATE_APPOINTMENT_ERROR";

export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";


/** Make Appointment */
export const FETCH_HOSPITALS = "FETCH_HOSPITALS";
export const FETCH_HOSPITALS_PENDING = "FETCH_HOSPITALS_PENDING";
export const FETCH_HOSPITALS_SUCCESS = "FETCH_HOSPITALS_SUCCESS";
export const FETCH_HOSPITALS_ERROR = "FETCH_HOSPITALS_ERROR";


/** Doctor Availability */
export const FETCH_DOCTOR_AVAILABILITY = "FETCH_DOCTOR_AVAILABILITY";
export const FETCH_DOCTOR_AVAILABILITY_PENDING = "FETCH_DOCTOR_AVAILABILITY_PENDING";
export const FETCH_DOCTOR_AVAILABILITY_SUCCESS = "FETCH_DOCTOR_AVAILABILITY_SUCCESS";
export const FETCH_DOCTOR_AVAILABILITY_ERROR = "FETCH_DOCTOR_AVAILABILITY_ERROR";

export const SAVE_DOCTOR_AVAILABILITY = "SAVE_DOCTOR_AVAILABILITY";
export const SAVE_DOCTOR_AVAILABILITY_PENDING = "SAVE_DOCTOR_AVAILABILITY_PENDING";
export const SAVE_DOCTOR_AVAILABILITY_SUCCESS = "SAVE_DOCTOR_AVAILABILITY_SUCCESS";
export const SAVE_DOCTOR_AVAILABILITY_ERROR = "SAVE_DOCTOR_AVAILABILITY_ERROR";

export const UPDATE_DOCTOR_AVAILABILITY = "UPDATE_DOCTOR_AVAILABILITY";
export const UPDATE_DOCTOR_AVAILABILITY_PENDING = "UPDATE_DOCTOR_AVAILABILITY_PENDING";
export const UPDATE_DOCTOR_AVAILABILITY_SUCCESS = "UPDATE_DOCTOR_AVAILABILITY_SUCCESS";
export const UPDATE_DOCTOR_AVAILABILITY_ERROR = "UPDATE_DOCTOR_AVAILABILITY_ERROR";


export const FETCH_DOCTOR_PATIENTS = "FETCH_DOCTOR_PATIENTS";
export const FETCH_DOCTOR_PATIENTS_PENDING = "FETCH_DOCTOR_PATIENTS_PENDING";
export const FETCH_DOCTOR_PATIENTS_SUCCESS = "FETCH_DOCTOR_PATIENTS_SUCCESS";
export const FETCH_DOCTOR_PATIENTS_ERROR = "FETCH_DOCTOR_PATIENTS_ERROR";

export const FETCH_DOCTOR_PATIENT_DETAILS = "FETCH_DOCTOR_PATIENT_DETAILS";
export const FETCH_DOCTOR_PATIENT_DETAILS_PENDING = "FETCH_DOCTOR_PATIENT_DETAILS_PENDING";
export const FETCH_DOCTOR_PATIENT_DETAILS_SUCCESS = "FETCH_DOCTOR_PATIENT_DETAILS_SUCCESS";
export const FETCH_DOCTOR_PATIENT_DETAILS_ERROR = "FETCH_DOCTOR_PATIENT_DETAILS_ERROR";

export const ADMIN_DOCTOR_API = "ADMIN_DOCTOR_API";
export const ADMIN_DOCTOR_API_PENDING = "ADMIN_DOCTOR_API_PENDING";
export const ADMIN_DOCTOR_API_SUCCESS = "ADMIN_DOCTOR_API_SUCCESS";
export const ADMIN_DOCTOR_API_ERROR = "ADMIN_DOCTOR_API_ERROR";