// ✅ Dashboard Actions
export const FETCH_DASHBOARD = "FETCH_DASHBOARD";
export const FETCH_DASHBOARD_PENDING = `FETCH_DASHBOARD_PENDING`;
export const FETCH_DASHBOARD_SUCCESS = `FETCH_DASHBOARD_SUCCESS`;
export const FETCH_DASHBOARD_ERROR = `FETCH_DASHBOARD_ERROR`;

export const SET_USER_AUTH = "SET_USER_AUTH";
export const LOGOUT_USER = "LOGOUT_USER";

export const LOGIN = "LOGIN";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const OAUTH_LOGIN = "OAUTH_LOGIN";
export const OAUTH_LOGIN_PENDING = "OAUTH_LOGIN_PENDING";
export const OAUTH_LOGIN_SUCCESS = "OAUTH_LOGIN_SUCCESS";
export const OAUTH_LOGIN_ERROR = "OAUTH_LOGIN_ERROR";

export const SIGNUP = "SIGNUP";
export const SIGNUP_PENDING = `SIGNUP_PENDING`;
export const SIGNUP_SUCCESS = `SIGNUP_SUCCESS`;
export const SIGNUP_ERROR = `SIGNUP_ERROR`;

export const OAUTH_SIGNUP = "OAUTH_SIGNUP";
export const OAUTH_SIGNUP_PENDING = `OAUTH_SIGNUP_PENDING`;
export const OAUTH_SIGNUP_SUCCESS = `OAUTH_SIGNUP_SUCCESS`;
export const OAUTH_SIGNUP_ERROR = `OAUTH_SIGNUP_ERROR`;

export const DOCTOR_ONBOARDING = "DOCTOR_ONBOARDING";
export const DOCTOR_ONBOARDING_PENDING = `DOCTOR_ONBOARDING_PENDING`;
export const DOCTOR_ONBOARDING_SUCCESS = `DOCTOR_ONBOARDING_SUCCESS`;
export const DOCTOR_ONBOARDING_ERROR = `DOCTOR_ONBOARDING_ERROR`;

export const PATIENT_ONBOARDING = "PATIENT_ONBOARDING";
export const PATIENT_ONBOARDING_PENDING = `PATIENT_ONBOARDING_PENDING`;
export const PATIENT_ONBOARDING_SUCCESS = `PATIENT_ONBOARDING_SUCCESS`;
export const PATIENT_ONBOARDING_ERROR = `PATIENT_ONBOARDING_ERROR`;

export const ROLE_SELECION = `ROLE_SELECION`;

export const UPLOAD_PROFILE_IMAGE = "UPLOAD_PROFILE_IMAGE";
export const UPLOAD_PROFILE_IMAGE_REQUEST = "UPLOAD_PROFILE_IMAGE_REQUEST";
export const UPLOAD_PROFILE_IMAGE_SUCCESS = "UPLOAD_PROFILE_IMAGE_SUCCESS";
export const UPLOAD_PROFILE_IMAGE_ERROR = "UPLOAD_PROFILE_IMAGE_ERROR";

