/**
 * @file Defines action type constants for Redux actions.
 * Includes authentication, onboarding, theme management, dashboard operations,
 * profile image uploads, and admin/doctor-specific actions.
 * @namespace store.actions.types
 * @memberof store.actions
 */

/** Theme Management */
export const SET_THEME = "SET_THEME";
export const SET_THEME_SUCCESS = "SET_THEME_SUCCESS";

/** Dashboard */
export const FETCH_DASHBOARD = "FETCH_DASHBOARD";
export const FETCH_DASHBOARD_PENDING = "FETCH_DASHBOARD_PENDING";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_ERROR = "FETCH_DASHBOARD_ERROR";

/** Authentication */
export const SET_USER_AUTH = "SET_USER_AUTH";
export const LOGOUT_USER = "LOGOUT_USER";

/** Login */
export const LOGIN = "LOGIN";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

/** OAuth Login */
export const OAUTH_LOGIN = "OAUTH_LOGIN";
export const OAUTH_LOGIN_PENDING = "OAUTH_LOGIN_PENDING";
export const OAUTH_LOGIN_SUCCESS = "OAUTH_LOGIN_SUCCESS";
export const OAUTH_LOGIN_ERROR = "OAUTH_LOGIN_ERROR";

/** Signup */
export const SIGNUP = "SIGNUP";
export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

/** OAuth Signup */
export const OAUTH_SIGNUP = "OAUTH_SIGNUP";
export const OAUTH_SIGNUP_PENDING = "OAUTH_SIGNUP_PENDING";
export const OAUTH_SIGNUP_SUCCESS = "OAUTH_SIGNUP_SUCCESS";
export const OAUTH_SIGNUP_ERROR = "OAUTH_SIGNUP_ERROR";

/** Doctor Onboarding */
export const DOCTOR_ONBOARDING = "DOCTOR_ONBOARDING";
export const DOCTOR_ONBOARDING_PENDING = "DOCTOR_ONBOARDING_PENDING";
export const DOCTOR_ONBOARDING_SUCCESS = "DOCTOR_ONBOARDING_SUCCESS";
export const DOCTOR_ONBOARDING_ERROR = "DOCTOR_ONBOARDING_ERROR";

/** Patient Onboarding */
export const PATIENT_ONBOARDING = "PATIENT_ONBOARDING";
export const PATIENT_ONBOARDING_PENDING = "PATIENT_ONBOARDING_PENDING";
export const PATIENT_ONBOARDING_SUCCESS = "PATIENT_ONBOARDING_SUCCESS";
export const PATIENT_ONBOARDING_ERROR = "PATIENT_ONBOARDING_ERROR";

/** Role Selection */
export const ROLE_SELECION = "ROLE_SELECION";

/** Profile Image Upload */
export const UPLOAD_PROFILE_IMAGE = "UPLOAD_PROFILE_IMAGE";
export const UPLOAD_PROFILE_IMAGE_REQUEST = "UPLOAD_PROFILE_IMAGE_REQUEST";
export const UPLOAD_PROFILE_IMAGE_SUCCESS = "UPLOAD_PROFILE_IMAGE_SUCCESS";
export const UPLOAD_PROFILE_IMAGE_ERROR = "UPLOAD_PROFILE_IMAGE_ERROR";

/** Admin Actions */
export const FETCH_DOCTORS = "FETCH_DOCTORS";
export const FETCH_DOCTORS_PENDING = "FETCH_DOCTORS_PENDING";
export const FETCH_DOCTORS_SUCCESS = "FETCH_DOCTORS_SUCCESS";
export const FETCH_DOCTORS_ERROR = "FETCH_DOCTORS_ERROR";

export const VERIFY_DOCTOR = "VERIFY_DOCTOR";
export const VERIFY_DOCTOR_PENDING = "VERIFY_DOCTOR_PENDING";
export const VERIFY_DOCTOR_SUCCESS = "VERIFY_DOCTOR_SUCCESS";
export const VERIFY_DOCTOR_ERROR = "VERIFY_DOCTOR_ERROR";

/** Doctor Actions */
export const UPLOAD_VERIFICATION_DOCS = "UPLOAD_VERIFICATION_DOCS";
export const UPLOAD_VERIFICATION_DOCS_PENDING =
  "UPLOAD_VERIFICATION_DOCS_PENDING";
export const UPLOAD_VERIFICATION_DOCS_SUCCESS =
  "UPLOAD_VERIFICATION_DOCS_SUCCESS";
export const UPLOAD_VERIFICATION_DOCS_ERROR = "UPLOAD_VERIFICATION_DOCS_ERROR";

/** Fetch Health Issue Actions */
export const FETCH_HEALTH_ISSUES = "FETCH_HEALTH_ISSUES";
export const FETCH_HEALTH_ISSUES_PENDING = "FETCH_HEALTH_ISSUES_PENDING";
export const FETCH_HEALTH_ISSUES_SUCCESS = "FETCH_HEALTH_ISSUES_SUCCESS";
export const FETCH_HEALTH_ISSUES_ERROR = "FETCH_HEALTH_ISSUES_ERROR";

/** Add Health Issue Actions */
export const ADD_HEALTH_ISSUE = "ADD_HEALTH_ISSUE";
export const ADD_HEALTH_ISSUE_PENDING = "ADD_HEALTH_ISSUE_PENDING";
export const ADD_HEALTH_ISSUE_SUCCESS = "ADD_HEALTH_ISSUE_SUCCESS";
export const ADD_HEALTH_ISSUE_ERROR = "ADD_HEALTH_ISSUE_ERROR";

/** Forgot Password */
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_PENDING = "FORGOT_PASSWORD_PENDING";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
