name: Staging CI/CD

on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - staging

jobs:
  test-frontend:
    name: Test Frontend (Staging)
    runs-on: ubuntu-latest
    env:
      CYPRESS_ENV: staging
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install Frontend Dependencies
        working-directory: ./Code/uspark-frontend
        run: npm install
      - name: Run Cypress Tests
        working-directory: ./Code/uspark-frontend
        run: npm run cy:run || true
      - name: Upload Cypress Test Artifacts to S3
        if: failure() # Only run if tests fail
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          aws s3 cp ./Code/uspark-frontend/cypress/screenshots s3://rush-hour-uploads/staging/cypress/$TIMESTAMP/screenshots --recursive
          aws s3 cp ./Code/uspark-frontend/cypress/videos s3://rush-hour-uploads/staging/cypress/$TIMESTAMP/videos --recursive
        env:
          AWS_ACCESS_KEY_ID: AKIAUBKFCORW7RLJKMZZ
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: us-east-2

  test-backend:
    name: Test Backend (Staging)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install Backend Dependencies
        working-directory: ./Code/uspark-backend
        run: |
          npm install
          echo "BASE_URL=https://two025s-rushhour.onrender.com" > .env
      - name: Run Backend Tests
        working-directory: ./Code/uspark-backend
        run: npm test

  deploy-staging:
    name: Deploy to Staging
    needs: [test-frontend, test-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 🚀 Deploy Frontend to Vercel
      - name: Deploy Frontend to Vercel
        working-directory: ./Code/uspark-frontend
        run: |
          npm install
          npm install -g vercel
          npm run stage  # Builds the frontend in the 'staging' folder
          vercel deploy --prod --confirm --token E1QGaNoYU3MapRGikZvu6jKW ./staging

      # 🚀 Deploy Backend to Render
      - name: Deploy Backend to Render
        working-directory: ./Code/uspark-backend
        run: |
          curl -X POST https://api.render.com/deploy/srv-cv76otogph6c73drjeag?key=9TpV9Mti7-c
